### ISSUE TITLE
Employer Insight Available for London Based Student

### ISSUE THREAD

**Issue by AmyL23** [yalla-coop/erica-playground#12]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

Medium

### Please describe your issue & include screenshots:

Was testing to see if Employer Insight choice page came up for a London based student, which it did, even though London students shouldn't be eligible for those. 

Tester Amy

**Comment by egasparini** [comment]
Closing this as it's a duplicate. Thanks for reporting it though Amy!
