### ISSUE TITLE
Wrong School Pulled Through to SF

### ISSUE THREAD

**Issue by AmyL23** [yalla-coop/erica-playground#26]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

Medium

### Please describe your issue & include screenshots:

Marking- SF has pulled through current school twice even though GCSE school is different. It has the different school written in text box underneath, just not pulled through as a field 

Tester Amy

### Page URL

<img width="618" alt="SF error" src="https://github.com/yalla-coop/smf-app-QA-repo/assets/142905898/18f5198c-b6a8-47b2-b95c-3d1ca0d8a42b">

**Comment by egasparini** [comment]
Good catch @AmyL23!
I have fixed this :)
