### ISSUE TITLE
Employer Insights London

### ISSUE THREAD

**Issue by RebeccaMil** [yalla-coop/erica-playground#28]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

Medium

### Please describe your issue & include screenshots:

Options for employer insight appeared when they shouldn't have. Rebecca Test 1

**Comment by Wah-AuSMF** [comment]
@egasparini I think we can use the new SF Dynamic Picklists feature on FormAssembly to avoid these type of issues in the future? I think it would be good to change this task to connect picklists to SF?

Unlikely a mapping issue but worth checking?

**Comment by egasparini** [comment]
@Wah-AuSMF first we need SF to pass the school city, then we can add some logic in the form so we don't display this page if it's a London student. 
Just to double check: is it enough to check the school address or do we want to base this ALSO on the home address?
