### ISSUE TITLE
Autosave not working 

### ISSUE THREAD

**Issue by RebeccaMil** [yalla-coop/erica-playground#29]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

Low

### Please describe your issue & include screenshots:

After first page, when I clicked next and then closed and reopened my details where there. 

After next pages (personal details onwards) when I closed it said my changes would not be saved if I left.

I left and when copied in link had to enter details again as they were not saved. This happened up until I submitted part 1. 

Then happened again after – after I clicked next on assessment questions I left and it hadn’t saved my progress. 

Rebecca Test 3

**Comment by egasparini** [comment]
Thanks for reporting this @RebeccaMil!
Someone else already reported it (see #34) so I will close it. 
Best,
Erica
