### ISSUE TITLE
Job Titles: Difficult to find

### ISSUE THREAD

**Issue by saffronspry** [yalla-coop/erica-playground#31]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Backlog / New idea, Bug

### Priority

Medium

### Please describe your issue & include screenshots:

I assessed the ease of use when searching for various common and uncommon job titles.

Jobs only show if students use commas between key words e.g. 'Administrator, personnel' appeared but 'Administrator personnel' did not. This could cause issues/confusion for students. 

Work arounds can be found for most job titles, but clarity with students is probably needed for how to select the correct choice. I believe there could be a lot of emails from students uncertain about which category to choose for parents jobs.

Having this confusion on the first page of the application form could be off-putting for students trying to apply, and offering them option to write their parents professions in a long text answer box may be better.
![Screenshot 2023-08-25 113800](https://github.com/yalla-coop/smf-app-QA-repo/assets/142818240/5a8edfa9-ad82-4801-86d2-d507c0370c37)
![Screenshot 2023-08-25 113817](https://github.com/yalla-coop/smf-app-QA-repo/assets/142818240/df65e865-d59f-4822-bf19-2afa4224c4e5)

### Page URL

https://smf-web-app.herokuapp.com/

**Comment by egasparini** [comment]
@Wah-AuSMF to advise how we want to proceed with this.

**Comment by Wah-AuSMF** [comment]
@egasparini Have spoken with team and we will address this in the copy. 

@dupreesi I've changed the copy to the below - could you please update:

_What is the occupation of your highest paid parent or guardian? *

Start by entering a general word which describes their role. E.g. Administrator. Next, scroll down the list to find the option which fits. Don't worry about getting the exact job title! You may also want to try reversing the words, e.g. Civil Servant = "Servant, Civil." If you're having trouble, finding the right option, try [searching here](https://onsdigital.github.io/dp-classification-tools/standard-occupational-classification/ONS_SOC_occupation_coding_tool.html) first. 

As long as you find an option which describes their occupation, you're good to go. 

If they're not currently in paid work but have had a job in the last three years or have recently retired? Enter their last occupation. Or, your guardian hasn't been in paid work? Select 'Unemployed'._

**Comment by egasparini** [comment]
Thanks @Wah-AuSMF!
@dupreesi will assign this to you, if you could sort it out this week it would be great. Thanks!

**Comment by dupreesi** [comment]
done @Wah-AuSMF @egasparini but just letting you know that it is a lot of explainer text on the page now:

<img width="401" alt="Bildschirmfoto 2023-08-31 um 19 43 11" src="https://github.com/yalla-coop/smf-app-QA-repo/assets/23721486/7fced97b-4e03-4245-89e4-a29e00a243d4">
<img width="1336" alt="Bildschirmfoto 2023-08-31 um 19 42 54" src="https://github.com/yalla-coop/smf-app-QA-repo/assets/23721486/5817ac7d-7036-4f16-8ff0-0b8108577631">

Let me know if I should update anything - could make it collapsable but I guess it works for now?

**Comment by egasparini** [comment]
@Wah-AuSMF, @dupreesi and I discuss this task this morning and adjusting the search functionality seems to be a rather big task. We expect it to take about 3 days. 
We don't have capacity for it this week and next week, but we could pick it up the first week of October. Would that work?

**Comment by Wah-AuSMF** [comment]
@dupreesi @egasparini 

Thanks for the update! Yes, if we can please schedule this in for w/c 2nd October.

I thought the search update might happen earlier so while before that change is made, can we please update the copy on the webapp this week?

"What is the main occupation of your highest paid parent or guardian? *

- Is your guardian recently retired or searching for work? Enter their latest job.
- If they have more than one job? Enter the one they’ve done the longest.
- Haven’t been in paid work? Enter 'Unemployed'.

Don’t worry about finding the exact job title, as long as you find an option which roughly describes their occupation, you're good to go!"

**Comment by Wah-AuSMF** [comment]
@dupreesi Hi Simon! Thanks again for already making a big improvement to the search! Here's the new copy for the webapp:

"What is the main occupation of your highest paid parent or guardian? *

- Is your guardian recently retired or searching for work? Enter their latest job.
- If they have more than one job? Enter the one they’ve done the longest.
- Haven’t been in paid work? Enter 'Unemployed'.

Don’t worry about finding the exact job title, as long as you find an option which roughly describes their occupation, you're good to go!"

**Comment by dupreesi** [comment]
@Wah-AuSMF search filter functions have been updated to fix above bug description (ignoring commas but also making it possible to use them) + requested content updates also have been deployed by now

**Comment by Wah-AuSMF** [comment]
Thanks @dupreesi - Seems to be working with no issue! 

However, a **_very low priority_** issue with the copy, a speech mark has been accidentally included in the content - please remove: 

![Image](https://github.com/yalla-coop/smf-app-QA-repo/assets/139127398/d9fed4e0-c0cf-4f66-87c8-1d1ce120634b)

- [ ] Remove " from copy. 

_Don’t worry about finding the exact job title, as long as you find an option which roughly describes their occupation, you're good to go!_
