### ISSUE TITLE
Character Limit

### ISSUE THREAD

**Issue by saffronspry** [yalla-coop/erica-playground#32]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

High

### Please describe your issue & include screenshots:

Allowed me to submit form despite putting 500 characters for first name, last name, and other qualification.

Email address only flagged as invalid when it didn't include @ or .com. When I added these in, the form allowed it to continue despite there being 500 characters. 
![Screenshot 2023-08-24 122434](https://github.com/yalla-coop/smf-app-QA-repo/assets/142818240/5f61cad1-35d8-4449-a0af-fd99128617a5)

### Page URL

https://socialmobility.tfaforms.net/5067220?tfa_3026=14%2F08%2F2007&tfa_3024=0018G00000ValwTQAR&tfa_3041=Cardinal+Allen+Catholic+High+School%2C+Fleetwood&tfa_7918=England&tfa_7916=0018G00000ValwTQAR&tfa_3043=Cardinal+Allen+Catholic+High+School%2C+Fleetwood&tfa_7920=England&tfa_3040=Unemployed&tfa_3067=0000&tfa_3073=Unemployed&tfa_3071=0000

**Comment by egasparini** [comment]
Add a limit of 100 characters for these fields.

**Comment by egasparini** [comment]
This is done. For consistency, I have applied the same limits also to First Name, Last Name & Emails of the Emergency Contacts in Form 2.
