### ISSUE TITLE
Entering email twice

### ISSUE THREAD

**Issue by saffronspry** [yalla-coop/erica-playground#33]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Backlog / New idea

### Priority

Low

### Please describe your issue & include screenshots:

It may be useful to ask students to enter their email twice to ensure they have submitted it correctly, as they often make spelling errors when entering their email address. This would help to avoid bounce backs when sending student comms.

**Comment by egasparini** [comment]
We won't do this, as we have added an email review on Form 2.
