### ISSUE TITLE
Unable to save form and restart

### ISSUE THREAD

**Issue by rebecca-mccann** [yalla-coop/erica-playground#34]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

Medium

### Please describe your issue & include screenshots:

I had the testing brief of copying the URL and reopening on a new page- however it didn't reopen, kept sending me back to the 'hidden fields' page just past the first (school) page. 
![image](https://github.com/yalla-coop/smf-app-QA-repo/assets/142805793/c1e91a7e-7c8f-4d3f-aa6b-7dd827eb1cdf)

Rebecca Mc

### Page URL

-	https://socialmobility.tfaforms.net/5067220?tfa_3026=30%2F05%2F1999&tfa_3024=0018G00000ValOFQAZ&tfa_3041=The+Blue+Coat+CofE+School&tfa_7918=England&tfa_7916=0018G00000ValOFQAZ&tfa_3043=The+Blue+Coat+CofE+School&tfa_7920=England&tfa_3040=Nurse&tfa_3067=2231&tfa_3073=N%2FA&tfa_3071=N%2FA

**Comment by egasparini** [comment]
@Wah-AuSMF this is not working because we have not enabled this feature in the form settings.
I just enabled it for both Forms. 
We also have the option to specify our own reply-to email address and reply-to name. For the moment I left the default ones, but please let me know if I should change them. 



![Image](https://github.com/yalla-coop/smf-app-QA-repo/assets/55511970/7db70cbd-c9a3-4c58-8072-f533996bf0ac)

**Comment by Wah-AuSMF** [comment]
Thanks Erica! If you could, please change the email to "app@socialmobility.org.uk"

**Comment by Wah-AuSMF** [comment]
@egasparini 

![Image](https://github.com/yalla-coop/smf-app-QA-repo/assets/139127398/83191b99-51f2-41a9-a4f2-9116c2db2b55)

When you click on 'Need assistance with this form?'  it currently shows this:

![Image](https://github.com/yalla-coop/smf-app-QA-repo/assets/139127398/b7b1f70c-c2b2-4be5-81ef-d8b498be527e)

Please update copy to:

**Would like some help with your application? We'd be more than happy to support! Send an email to: app@socialmobility.org.uk**

**Comment by egasparini** [comment]
@Wah-AuSMF we will need to ask FormAssembly next week about this, because I cannot find it anywhere in the system.

**Comment by Wah-AuSMF** [comment]
Have updated via General Settings as advised by FA. Contact information now appears! @egasparini 

![Image](https://github.com/yalla-coop/smf-app-QA-repo/assets/139127398/88a2f6d1-7d50-4942-a3bb-581f7ca16834)

**Comment by egasparini** [comment]
Yay! That's amazing :)
Will close this task @Wah-AuSMF thanks for the update.
