### ISSUE TITLE
Reach prompt not appearing

### ISSUE THREAD

**Issue by rebecca-mccann** [yalla-coop/erica-playground#35]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

Medium

### Please describe your issue & include screenshots:

I had the testing brief to check if an other city school prompted APP Reach application however it let me submit a normal application and APP Reach only appeared in hidden fields box.

![image](https://github.com/yalla-coop/smf-app-QA-repo/assets/142805793/a1286286-cf7a-4f84-82a6-dd0708354e25)

Rebecca Mc

### Page URL

https://www.tfaforms.com/wfeaJAk/aa472092-5ebb-4948-8a20-a50a273cd648/XlDqgbpVn42TJ5YbKKIVoqg60keFrFIf%3A6a30e6851d0d8590faaed78206d3aebc

**Comment by egasparini** [comment]
@Wah-AuSMF is this something you could help with? 
I am not sure what the issue is in this case. Thanks!

**Comment by egasparini** [comment]
As discussed with Wah, this is working as expected. Thanks!
