### ISSUE TITLE
Counterintuitive previous/next?

### ISSUE THREAD

**Issue by rebecca-mccann** [yalla-coop/erica-playground#38]
### Device

iPhone

### What browsers are you seeing the problem on?

Safari

### What kind of issue is it?

Backlog / New idea

### Priority

Low

### Please describe your issue & include screenshots:

When you have the form open on a phone or on a splitscreen on a desktop, the 'previous' button goes above the 'next' button at the bottom. It then becomes counterintuitive (for me at least) because I kept clicking the previous button wanting to progress through the form. Is it worth thinking about whether they should be the other way around or is this too confusing? JUst a thought!

![image](https://github.com/yalla-coop/smf-app-QA-repo/assets/142805793/62fd21d9-ab97-46d0-8043-56b477f3c822)
 Rebecca Mc

### Page URL

https://www.tfaforms.com/5067221?tfa_21=0038G00000dhkvS&tfa_22=England&tfa_10=No&tfa_670=Banking%20&%20Finance&tfa_696=Engineering%20&%20Physics&tfa_18=Reach

**Comment by egasparini** [comment]
Thanks @rebecca-mccann, we'll add this request to the backlog for now.

**Comment by egasparini** [comment]
We will leave this as it is for now.
