### ISSUE TITLE
Crompton House school not on there

### ISSUE THREAD

**Issue by rebecca-mccann** [yalla-coop/erica-playground#39]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

Medium

### Please describe your issue & include screenshots:

Crompton House, a school we work with in Manchester, isn't on the form

![image](https://github.com/yalla-coop/smf-app-QA-repo/assets/142805793/314d21ed-0f1b-4b6b-9a1a-d29c3645b3c0)

Rebecca MC

### Page URL

https://smf-web-app.herokuapp.com/

**Comment by egasparini** [comment]
@Wah-AuSMF I leave this for you to check. It could be that the school is not there because we only have a subset of schools in the test environment, or it could be that we don't have it in production either.

**Comment by Wah-AuSMF** [comment]
@egasparini I have found this school in production so this can be closed - thanks!
