### ISSUE TITLE
Home telephone number requirement 

### ISSUE THREAD

**Issue by MorwennaSilver** [yalla-coop/erica-playground#40]
### Device

MacBook

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Backlog / New idea

### Priority

Medium

### Please describe your issue & include screenshots:

Landline phones are something that a lot (maybe even most) people don't have anymore. However, this is still a mandatory field on the application form. I think it would be a good idea not to have it as a required field. 

Tester: Mo

**Comment by Wah-AuSMF** [comment]
Have updated to change home phone to an optional field.
