### ISSUE TITLE
Parent occupation field - hard to navigate  

### ISSUE THREAD

**Issue by MorwennaSilver** [yalla-coop/erica-playground#41]
### Device

MacBook

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Copy

### Priority

Medium

### Please describe your issue & include screenshots:

The parent occupation field is very hard to navigate. It gives a very long list of options, some of which seem to be describing the same thing. This is difficult for young people and could stop applications because it's confusing.

Tester: Mo

**Comment by AntHad** [comment]
Seconding this. The data set it draws on makes for really bad UX.

There are 24 entries for 'handyman'. Surely we don't need to go that granular!

Applicants are 16-years-old and won't have too much patience for this.

Some more examples:

**Plumber**
<img width="307" alt="Screenshot 2023-08-30 at 12 12 09" src="https://github.com/yalla-coop/smf-app-QA-repo/assets/109097038/2bc876fa-fcac-4d8f-8906-ff2e923f1151">

**Bricklayer**
<img width="441" alt="Screenshot 2023-08-30 at 12 12 20" src="https://github.com/yalla-coop/smf-app-QA-repo/assets/109097038/6e46a0e4-80b1-4971-bd12-0b02cb72d228">
