### ISSUE TITLE
Missing A-level option 

### ISSUE THREAD

**Issue by MorwennaSilver** [yalla-coop/erica-playground#42]
### Device

MacBook

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Copy

### Priority

Medium

### Please describe your issue & include screenshots:

I noticed that A-Level Politics is missing from the list of subjects. I think this is important since politics is one of the sector areas we focus on.

Tester: Mo

**Comment by Wah-AuSMF** [comment]
In addition, one of my colleagues has told me there is a missing GCSE option for Northern Ireland:

![image](https://github.com/yalla-coop/smf-app-QA-repo/assets/139127398/9b9c076a-b16a-49b3-9a71-678070caee15)

- [x] Add GCSE Further Mathematics on FA and SF @egasparini

**Comment by egasparini** [comment]
@Wah-AuSMF Both subjects have been added, ready for your review.
