### ISSUE TITLE
Ability to exit long-answer section 

### ISSUE THREAD

**Issue by MorwennaSilver** [yalla-coop/erica-playground#43]
### Device

MacBook

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Copy

### Priority

Medium

### Please describe your issue & include screenshots:

Once students get to the long answer section, it might be useful here to have a line of copy saying whether students can exit the form at this point and have their answers saved. Or, stating if this is not the case and their answers will be lost. Some might want to go away and work on their answers over several days.

Tester: Mo

**Comment by egasparini** [comment]
We have enabled the functionality to save the form and continue later. I tested it and I can confirm that it retains all the previously entered information, including half written (or fully written!) answers to the Assessment Questions.
