### ISSUE TITLE
Marking - target city not pulled through 

### ISSUE THREAD

**Issue by RebeccaMil** [yalla-coop/erica-playground#44]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

Medium

### Please describe your issue & include screenshots:

Not sure if this issue is just because I didn't write a proper address, just a postcode for each test but the target city doesn't pull through on SF when marking (this is on most of my tests - but again might be because the address itself isn't properly filled in).

![image](https://github.com/yalla-coop/smf-app-QA-repo/assets/142986738/49c9947e-101e-4145-ba8d-5a7cf73879e3)

### Page URL

https://socialmobilityfoundation--101.sandbox.lightning.force.com/lightning/r/Contact/0038G00000dhGvQQAU/view

**Comment by egasparini** [comment]
This is most likely because post-code.io isn't running on the test environment. 
I will confirm with Thao today.

**Comment by egasparini** [comment]
Closing this as it's a duplicate.
