### ISSUE TITLE
Ryan Test 9

### ISSUE THREAD

**Issue by RyanMSMF** [yalla-coop/erica-playground#48]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Microsoft Edge

### What kind of issue is it?

Bug

### Priority

Medium

### Please describe your issue & include screenshots:

Instructions: Enter selective school "Bexlety Grammar School", correct age (16-17), no to Free Schools Meals, no to First Generation, High Income (higher than £45,001). Select 'Yes for being a Young Carer' but NOT for 'Care-Experienced'

Expected outcome: Able to submit form but will will receive email / notification to say they do not meet criteria. 

Issue: Unable to move past first page. Came up that they do not accept students from private schools. (Ryan Test 9)

**Comment by Wah-AuSMF** [comment]
This can be closed - ineligible page appeared properly.
