### ISSUE TITLE
(Ryan Test 14, was able to submit form but was not prompted to apply for reach)

### ISSUE THREAD

**Issue by RyanMSMF** [yalla-coop/erica-playground#49]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Microsoft Edge

### What kind of issue is it?

Bug

### Priority

High

### Please describe your issue & include screenshots:

Should have been prompted to apply for reach. (Ryan Test 14, was able to submit form but was not prompted to apply for reach)

**Comment by egasparini** [comment]
This is Ryan Test 14's application in salesforce: https://socialmobilityfoundation--101.sandbox.lightning.force.com/lightning/r/Contact/0038G00000djEHcQAM/view
