### ISSUE TITLE
Ethnicity Drop down order

### ISSUE THREAD

**Issue by IndiaH956** [yalla-coop/erica-playground#52]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### Priority

Low

### Please describe your issue & include screenshots:

Tricky to find the correct ethnicity selection as they are not alphabetical.

**Comment by Wah-AuSMF** [comment]
Have contacted colleague to get latest list of ethnicities based on official guidance. 

FYI: Official bodies and their suggestions: [HESA](https://www.hesa.ac.uk/collection/student/datafutures/a/student_ethnic) and [UCAS](https://www.ucas.com/sites/default/files/mismanual_appendixa_1.xlsx)

**Comment by egasparini** [comment]
Thanks @Wah-AuSMF!
I see that the HESA is applicable to the whole of the UK, while the UCAS seems to be specific to England and Wales.
Should we adjust our dropdown to match the list on the HESA website?

**Comment by Wah-AuSMF** [comment]
Let's hold off until I hear back from my colleague - they will be analysing this data later so I want to get approval from them first :)

**Comment by Wah-AuSMF** [comment]
@egasparini Heard back from the team! For now, the decision is to just the **alphabetise the current list**. We will add to our internal backlog to review the options next year, to ensure we're following best practice. 

- [x] Alphabetise the Ethnicity drop-down options.

**Comment by egasparini** [comment]
Done @Wah-AuSMF :)
