### ISSUE TITLE
Other Qualification - No Character Limit

### ISSUE THREAD

**Issue by IndiaH956** [yalla-coop/erica-playground#54]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Backlog / New idea

### Priority

Low

### Please describe your issue & include screenshots:

Other qualification in the ‘please specifiy’ box there doesn’t seem to be a character limit.

**Comment by egasparini** [comment]
Let's make it 100 characters
