### ISSUE TITLE
Error Page after Submission of Form 1 - India Test 7

### ISSUE THREAD

**Issue by IndiaH956** [yalla-coop/erica-playground#55]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

High

### Please describe your issue & include screenshots:

I got an error page when submitting form 1. Refreshed as instructed and thank you page popped up as normal but no email and then error page returned so i could not complete the application. India

**Comment by egasparini** [comment]
This has been solved.
