### ISSUE TITLE
Salesforce: Sector Preference Naming Error (&)

### ISSUE THREAD

**Issue by Wah-AuSMF** [yalla-coop/erica-playground#65]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Chrome

### What kind of issue is it?

Bug

### Priority

Medium

### Please describe your issue & include screenshots:

<img width="317" alt="image" src="https://github.com/yalla-coop/smf-app-QA-repo/assets/139127398/98e7771f-a8a7-4a12-860a-e244c7e63d26">

Sectors which include "&" in the name are showing incorrectly on Salesforce.

### Page URL

https://socialmobilityfoundation--101.sandbox.lightning.force.com/lightning/r/Contact/0038G00000dkHBHQA2/view

**Comment by egasparini** [comment]
This is fixed now @Wah-AuSMF, there was a mis-match in the naming convention between Form 1 and Form 2. I've
corrected it and now all sector preferences should always come in with "and" instead of "&".
